### ISSUE TITLE
R CMD check NOTEs

### ISSUE THREAD

**Issue by hadley** [LiveOak/NlsyLinks#15]
When checking NlysLinks (as part of the revdep process for devtools), I see

```
checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘methods’
  All declared Imports should be used.
See the information on DESCRIPTION files in the chapter ‘Creating R
packages’ of the ‘Writing R Extensions’ manual.
```
```
checking R code for possible problems ... NOTE
ReadCsvNlsy79Gen1: no visible binding for global variable
  ‘SubjectDetails79’
ReadCsvNlsy79Gen2: no visible binding for global variable
  ‘SubjectDetails79’
```

This means you've forgotten to import the methods package, and it looks like you might be using the wrong data setup if SubjectDetails79 is a dataset needed by the functions in your package.

**Comment by wibeasley** [comment]
Thanks for the advice @hadley, even though it wasn't devtools's problem.  I didn't change anything in the description file after switching the reference from 
```r
dsWithExtended <- SubjectDetails79[SubjectDetails79$Generation==2, c("SubjectTag", "ExtendedID")]
```

to 
```r
d <- NlsyLinks::SubjectDetails79
...
dsWithExtended <- d[d$Generation==2, c("SubjectTag", "ExtendedID")]
```

Things pass locally, Travis, and winbuilder (http://win-builder.r-project.org/dzCYzjKCsQcV/00check.log).  I'll submit the new version to CRAN, so they potentially hassle you less
